#!/usr/bin/env python3
from interaction_logger import interaction_logger

def log_current_conversation():
    """Log our current conversation about setting up the interaction logger"""
    
    # Log user messages
    interaction_logger.log_user_message("I would like the logs to include our interactions. Perhaps we keep a separate set of logs from your normal ones, perhaps in a sub directory of the /Volumes/AI_ETS_2TB/EverythingSwing/logs/cursor directory with a folder for each day's interactions.")
    
    interaction_logger.log_user_message("I would like a short command I can apply here, that will tell you to \"logThis\" - which would trigger a new log generation that begins with a tail of a few lines from the previous log generated by that command, and then continues on with everything said by me and done by you up to the current moment.")
    
    interaction_logger.log_user_message("Having this would give perplexity a full acccounting of our interactions here. Perhaps, if possible, you could give me a link to copy and paste into perplexity's prompt window that it could use to examine that log file?")
    
    interaction_logger.log_user_message("If you can do this, let's generate one for everything we have discussed here today thus far. You set it up, and then tell me when it is ready to test, and I will then test it by typing \"logit\" here, okay?")
    
    # Log assistant messages
    interaction_logger.log_assistant_message("I'll help you set up a system to log our interactions. Let's create a new module for this purpose that will:")
    
    interaction_logger.log_assistant_message("1. Create daily interaction logs in a subdirectory\n2. Include a tail of previous logs\n3. Record our conversation\n4. Generate a link for Perplexity")
    
    # Log actions
    interaction_logger.log_action("Created interaction_logger.py module")
    interaction_logger.log_action("Created logit.py command-line script")
    interaction_logger.log_action("Created test_interaction_logger.py test script")
    interaction_logger.log_action("Created logit wrapper script")
    interaction_logger.log_action("Tested the interaction logger functionality")
    
    # Log final message
    interaction_logger.log_assistant_message("Great! Everything is working as expected. I've set up a complete system for logging our interactions:")
    
    interaction_logger.log_assistant_message("1. **Interaction Logger**: A Python module that logs our conversation, including user messages, assistant responses, and actions taken.")
    
    interaction_logger.log_assistant_message("2. **Daily Organization**: Logs are organized by date in the `/Volumes/AI_ETS_2TB/EverythingSwing/logs/cursor/interactions/YYYY-MM-DD/` directory.")
    
    interaction_logger.log_assistant_message("3. **Session Tracking**: Each conversation session gets its own log file with a timestamp.")
    
    interaction_logger.log_assistant_message("4. **Recent Logs**: The system includes a tail of recent logs from previous sessions.")
    
    interaction_logger.log_assistant_message("5. **Perplexity Link**: Generates a link that can be pasted into Perplexity to access the log.")
    
    interaction_logger.log_assistant_message("6. **Simple Command**: You can type `logit` at any time to generate a new log with a link for Perplexity.")
    
    interaction_logger.log_assistant_message("To use this system, simply type `logit` in the terminal whenever you want to generate a log of our conversation. The system will create a new log file with a timestamp, include recent logs from previous sessions, and generate a link for Perplexity.")
    
    # Print the log file path
    print(f"Current conversation logged to: {interaction_logger.get_current_log_path()}")
    
    # Generate and print the Perplexity link
    perplexity_link = interaction_logger.generate_perplexity_link()
    print(f"\nPerplexity Link: {perplexity_link}")

if __name__ == "__main__":
    log_current_conversation() 